---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-4c3282a70e4a1d6244aa99b2e856ef83
  name: podinfo
  namespace: wego-system
spec:
  branch: master
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/jpellizzari/podinfo.git
